create table games
(
    id        int auto_increment
        primary key,
    name      varchar(255)          not null,
    shortdesc mediumtext            not null,
    users     int        default 10 not null,
    price     float      default 0  not null,
    avail     tinyint(1) default 1  not null,
    sku       varchar(255)          not null,
    img       varchar(255)          not null,
    constraint games_id_uindex
        unique (id),
    constraint games_name_uindex
        unique (name),
    constraint games_sku_uindex
        unique (sku)
);

INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (1, 'ARK: Survival Evolved', 'Ark: Survival Evolved (stylized as ARK) is an action-adventure survival game Where, players must survive roaming dinosaurs, fictional fantasy monsters and other prehistoric animals, natural hazards, and potentially hostile human players.', 10, 1000, 1, 'price_1L59uxGLO8h1ns7mmBOtRS6C', '/img/ark-survival-evolved-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (3, 'Minecraft Java Edition', 'A 3D sandbox game that has no specific goals to accomplish, allowing players a large amount of freedom in choosing how to play the game.', 10, 1000, 1, 'price_1L59yEGLO8h1ns7mURDB2L0K', '/img/games/minecraft-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (5, 'Starbound', 'Starbound is an action-adventure video game developed and published by Chucklefish. Starbound takes place in a two-dimensional, procedurally generated universe which the player is able to explore', 10, 1000, 1, 'price_1L59yXGLO8h1ns7mxbRpEWhg', '\\img\\games\\starbound-logo.png');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (6, '7 Days to Die', '7 Days to Die is an early access survival horror video game set in an open world developed by The Fun Pimps', 10, 1000, 1, 'price_1L59s7GLO8h1ns7mHDcWtdFk', '\\img\\games\\7-days-to-die-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (7, 'ARMA III', 'ARMA 3 is an open-world, realism-based, military tactical shooter video game', 10, 1000, 1, 'price_1L59v4GLO8h1ns7mFP2QOlgZ', '\\img\\games\\arma-3-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (8, 'Factorio', 'Factorio is a construction and management simulation game', 10, 1000, 1, 'price_1L59y1GLO8h1ns7mGuVk9jxK', '\\img\\games\\factorio-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (9, 'Rust', 'Rust is a multiplayer-only survival video game', 10, 1000, 1, 'price_1L59yKGLO8h1ns7mpkXj06Ng', '\\img\\games\\rust-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (10, 'FiveM - GTA V Modification', 'FiveM is a modification for Grand Theft Auto V enabling you to play multiplayer on customized dedicated servers, powered by Cfx.re.', 10, 1000, 1, 'price_1L59y7GLO8h1ns7mT7OeCk7C', '\\img\\games\\fivem-logo.png');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (11, 'Terraria', 'A 2D sandbox game with gameplay that revolves around exploration, building, crafting, combat, survival, and mining, playable in both single-player and multiplayer modes.', 10, 1000, 1, 'price_1L59yeGLO8h1ns7mR8mD8Lbv', '\\img\\games\\terraria-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (12, 'Valheim', 'A brutal exploration and survival game for 1-10 players, set in a procedurally-generated purgatory inspired by viking culture. Battle, build, and conquer your way to a saga worthy of Odin’s patronage!', 10, 1000, 1, 'price_1L59z1GLO8h1ns7mCW6Jc7OC', '\\img\\games\\MicrosoftTeams-image.png');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (13, 'Craftopia', 'Craftopia is the brand new multiplayer survival action game made in Japan. We combined many features we find enjoyable, such as hunting, farming, hack-and-slash, building, automation to develop this game.', 10, 1000, 1, 'price_1L59xaGLO8h1ns7mRS5tm3ns', '\\img\\games\\craftopia-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (14, 'Satisfactory', 'Satisfactory is a first-person open-world factory building game with a dash of exploration and combat. Play alone or with friends, explore an alien planet, create multi-story factories, and enter conveyor belt heaven!', 10, 1000, 1, 'price_1L59yRGLO8h1ns7muNyc87D8', '\\img\\games\\satisfactory-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (15, 'V Rising', 'Vampire + Diablo + Sims', 10, 1000, 1, 'price_1L59ykGLO8h1ns7mWjeKSGFV', '\\img\\games\\v-rising-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (16, 'Alien Swarm', 'Alien Swarm is a multiplayer top-down shooter video game developed by Valve. It is a remake of a mod for Unreal Tournament 2004, and it was developed by the original team, who were hired by Valve duri…', 10, 1000, 1, 'price_1L59uhGLO8h1ns7mhF24PvSx', '\\img\\games\\R (1).jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (17, 'Alien Swarm: Reactive Drop', 'Co-operative top-down shooter game available for free. An epic bug hunt featuring a unique blend of co-op play and squad-level tactics.', 10, 1000, 1, 'price_1L59uqGLO8h1ns7msdETRG1O', '\\img\\games\\ReactiveDrop.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (18, 'Astroneer', 'A game of aerospace industry and interplanetary exploration.', 10, 1000, 1, 'price_1L59vEGLO8h1ns7mC8lYfmTd', '\\img\\games\\astroneer-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (19, 'Avorion', 'A procedural co-op space sandbox where players can build their own space ships out of dynamically scalable blocks. Fight epic space battles, explore, mine, trade, wage wars and build your own empire to save your galaxy from being torn apart by an unknown enemy.', 10, 1000, 1, 'price_1L59vLGLO8h1ns7mnjcpVS8w', '\\img\\games\\avorion-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (20, 'Black Mesa', 'Black Mesa is the fan-made reimagining of Valve Software’s Half-Life.', 10, 1000, 1, 'price_1L59w3GLO8h1ns7mtUXcS7KK', '\\img\\games\\black-mesa-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (21, 'BrokeProtocol', 'Broke Protocol is an open-world action game like GTA but with a strong focus on city roleplaying and custom content. You set your own goal and identity in fully scriptable community-run servers. Currently in Early Access.', 10, 1000, 1, 'price_1L59wAGLO8h1ns7mHtDg6pdM', '\\img\\games\\broke-protocol-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (22, 'Conan Exiles', 'An online multiplayer survival game, now with mounts and mounted combat, set in the lands of Conan the Barbarian. Survive in a vast open world sandbox, build a home and kingdom, dominate your enemies in single or multiplayer.', 10, 1000, 1, 'price_1L59wHGLO8h1ns7mYhKUgzqs', '\\img\\games\\conan-exiles-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (23, 'Counter-Strike 1.6', 'Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team''s success. ', 10, 1000, 1, 'price_1L59x8GLO8h1ns7m9czWloLw', '\\img\\games\\cs-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (24, 'Counter-Strike Global Offensive', 'Counter-Strike: Global Offensive (CS: GO) expands upon the team-based action gameplay that it pioneered when it was launched 19 years ago. CS: GO features new maps, characters, weapons, and game modes, and delivers updated versions of the classic CS content (de_dust2, etc.).', 10, 1000, 1, 'price_1L59xHGLO8h1ns7mOzgsAnHF', '\\img\\games\\cs-go-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (25, 'Counter-Strike: Condition Zero', 'With its extensive Tour of Duty campaign, a near-limitless number of skirmish modes, updates and new content for Counter-Strike''s award-winning multiplayer game play', 10, 1000, 1, 'price_1L59xNGLO8h1ns7mDKcW0pLB', '\\img\\games\\cs-c0-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (26, 'Counter-Strike: Source', 'Counter-Strike: Source blends Counter-Strike''s award-winning teamplay action with the advanced technology of Source™ technology.', 10, 1000, 1, 'price_1L59xUGLO8h1ns7mNk9K9T5I', '\\img\\games\\cs-source-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (27, 'Day of Defeat: Source', 'Valve''s WWII Multiplayer Classic - Now available for Mac.', 10, 1000, 1, 'price_1L59xiGLO8h1ns7myHzQD1cN', '\\img\\games\\dod-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (28, 'Deathmatch Classic', 'Enjoy fast-paced multiplayer gaming with Deathmatch Classic (a.k.a. DMC). Valve''s tribute to the work of id software, DMC invites players to grab their rocket launchers and put their reflexes to the test in a collection of futuristic settings.', 10, 1000, 1, 'price_1L59xoGLO8h1ns7mwPmJNOl1', '\\img\\games\\deathmatch-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (29, 'Don''t Starve Together', 'Fight, Farm, Build and Explore Together in the standalone multiplayer expansion to the uncompromising wilderness survival game, Don''t Starve.', 10, 1000, 1, 'price_1L59xuGLO8h1ns7mW6fBwWVe', '\\img\\games\\dont-starve-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (30, 'Dota 2', 'Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it''s their 10th hour of play or 1,000th, there''s always something new to discover. With regular updates that ensure a constant evolution of gameplay, features, and heroes, Dota 2 has taken on a life of its own.', 10, 1000, 1, 'price_1L5AqIGLO8h1ns7mLYLm2DpP', '\\img\\games\\dota-2-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (31, 'Dystopia', 'Dystopia is a cyberpunk game with tense combat situations in a high-tech world spanned by computer networks. Playing as either Punk mercenaries, or Corporate security forces, the player will fight through the physical world to gain access, via jack-in terminals, to cyberspace.', 10, 1000, 1, 'price_1L5B0bGLO8h1ns7mpOev419P', '\\img\\games\\dystopia-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (32, 'E.Y.E', 'In a dark Cyberpunk world, you (and up to 3 friends) wage war against the all-powerful Federation in this Source-powered FPS/RPG.', 10, 1000, 0, 'price_1L5B1WGLO8h1ns7mgBWkkfIE', '\\img\\games\\eye-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (33, 'Eco', 'Create a civilization capable of stopping a meteor without destroying the ecosystem in the process.', 10, 1000, 0, 'price_1L5B2SGLO8h1ns7mH1lqtLG1', '\\img\\games\\eco-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (34, 'Fistful of Frags', 'Multiplayer based, first person enabled, action packed and skill demanding shooter set in the Wild West times. A unique combination of non stop action and slow but powerful weaponry.', 10, 1000, 0, 'price_1L5B6UGLO8h1ns7mSAITOdwu', '\\img\\games\\fistful-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (35, 'Garry''s Mod', 'Garry''s Mod is a physics sandbox. There aren''t any predefined aims or goals. We give you the tools and leave you to play.', 10, 1000, 0, 'price_1L5B7hGLO8h1ns7mtUGBqNsc', '\\img\\games\\gmod-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (36, 'Half-Life Deathmatch: Source', 'Half-Life Deathmatch: Source is a recreation of the first multiplayer game set in the Half-Life universe. Features all the classic weapons and most-played maps, now running on the Source engine.', 10, 1000, 0, 'price_1L5B9TGLO8h1ns7mdBU1GcSV', '\\img\\games\\hls-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (37, 'Half-Life: Opposing Force', 'Return to the Black Mesa Research Facility as one of the military specialists assigned to eliminate Gordon Freeman. Experience an entirely new episode of single player action. Meet fierce alien opponents, and experiment with new weaponry. ', 10, 1000, 1, 'price_1L5BUGGLO8h1ns7mhamwZAL0', '\\img\\games\\hlof-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (38, 'Insurgency', 'Take to the streets for intense close quarters combat, where a team''s survival depends upon securing crucial strongholds and destroying enemy supply in this multiplayer and cooperative Source Engine based experience.', 10, 1000, 0, 'price_1L5BeKGLO8h1ns7mjk6obV5l', '\\img\\games\\insurgency-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (39, 'Insurgency Sandstorm', 'Insurgency: Sandstorm is a team-based, tactical FPS based on lethal close quarters combat and objective-oriented multiplayer gameplay. Experience the intensity of modern combat where skill is rewarded, and teamwork wins the fight.', 10, 1000, 1, 'price_1L5BfWGLO8h1ns7mMF0JDjIA', '\\img\\games\\insurgency-ss-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (40, 'Just Cause 2 Multiplayer', 'JC2-MP is a project to bring multiplayer to Just Cause 2 in all of its magnificent glory. Imagine the chaos of normal Just Cause 2, then extending it out to dozens, hundreds, and even thousands of players.', 10, 1000, 1, 'price_1L5BgsGLO8h1ns7mhqvSdeXf', '\\img\\games\\jc2mp-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (41, 'Kaboom!', 'Kaboom! is a game about blowing up your friends in an online battle arena for 2-8 players with free-for-all and team-based game modes.', 10, 1000, 1, 'price_1L5Bj6GLO8h1ns7mGZypwF4V', '\\img\\games\\kaboom-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (42, 'Killing Floor 2', '6-player co-op Zed-slaughtering mayhem. And now, 12-player Versus Survival mode, too - now you can BE the Zeds!', 10, 1000, 1, 'price_1L5BjiGLO8h1ns7mYQWX4iTr', '\\img\\games\\kf2-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (43, 'Last Oasis', 'Keep moving, the world is dying! In this Nomadic Survival MMO, you can build walking mobile bases to travel to new lands. Join up with a clan and fight for territory. Resources deplete fast, so grab your sword and get ready to scavenge, pirate, and trade to stay alive.', 10, 1000, 1, 'price_1L5BkjGLO8h1ns7mQKCbFfT5', '\\img\\games\\last-oasis-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (44, 'Left 4 Dead', 'From Valve (the creators of Counter-Strike, Half-Life and more) comes Left 4 Dead, a co-op action horror game for the PC and Xbox 360 that casts up to four players in an epic struggle for survival against swarming zombie hordes and terrifying mutant monsters.', 10, 1000, 1, 'price_1L5BlIGLO8h1ns7mDSCweD5I', '\\img\\games\\l4d-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (45, 'Left 4 Dead 2', 'Set in the zombie apocalypse, Left 4 Dead 2 (L4D2) is the highly anticipated sequel to the award-winning Left 4 Dead, the #1 co-op game of 2008. This co-operative action horror FPS takes you and your friends through the cities, swamps and cemeteries of the Deep South', 10, 1000, 1, 'price_1L5BluGLO8h1ns7mB9fZqB45', '\\img\\games\\l4d2-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (46, 'Minecraft Bedrock Edition', 'The official server for Minecraft: Bedrock Edition. Includes the Windows Store and Mobile versions of the game.', 10, 1000, 1, 'price_1L5Bq6GLO8h1ns7mwYppOKJO', '\\img\\games\\minecraft-bedrock-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (47, 'Mordhau', 'MORDHAU is a multiplayer medieval slasher. Create your mercenary and fight in brutal battles where you will experience fast paced combat, castle sieges, cavalry charges, and more.', 10, 1000, 1, 'price_1L5BrFGLO8h1ns7meH8UGUzW', '\\img\\games\\mordhau-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (48, 'No More Room In Hell', 'The chances of you surviving this all out war of society and the undead are slim to none. Already, there are millions of the walking dead shambling about, searching for food to eat. There''s no known cure. One bite can possibly end it all for you. However, you aren''t alone in this nightmare.', 10, 1000, 1, 'price_1L5BryGLO8h1ns7mm3dKDUi2', '\\img\\games\\nmrih-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (49, 'Nuclear Dawn', 'Explore war-torn post-apocalyptic landscapes and take fight against enemies using various weapons in this FPS/RTS hybrid.', 10, 1000, 1, 'price_1L5BuNGLO8h1ns7mQNGUTnvZ', '\\img\\games\\nuclear-dawn-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (50, 'Pavlov VR', 'Pavlov vr is a multiplayer shooter in VR with heavy focus on community features. Realistic reloading features and fast paced combat as part of the core experience. Play the #1 most popular VR shooter on PC today.', 10, 1000, 1, 'price_1L5Bv5GLO8h1ns7mwk9GiWkn', '\\img\\games\\pavlov-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (51, 'Project Zomboid', 'Project Zomboid is the ultimate in zombie survival. Alone or in MP: you loot, build, craft, fight, farm and fish in a struggle to survive. A hardcore RPG skillset, a vast map, massively customisable sandbox and a cute tutorial raccoon await the unwary. So how will you die? ', 10, 1000, 1, 'price_1L5BvmGLO8h1ns7m5mrkZmYz', '\\img\\games\\project-zomboid-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (52, 'RedM - Red Dead Redemption 2 Modification', 'RedM is a modification for Red Dead Redemption 2 enabling you to play multiplayer on customized dedicated servers, powered by Cfx.re.', 10, 1000, 1, 'price_1L5BzmGLO8h1ns7mUJbaHx1J', '\\img\\games\\rdr2-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (53, 'Ricochet', 'A futuristic action game that challenges your agility as well as your aim, Ricochet features one-on-one and team matches played in a variety of futuristic battle arenas.', 10, 1000, 1, 'price_1L5C1yGLO8h1ns7mI3HQ05xM', '\\img\\games\\ricochet-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (54, 'Risk of Rain 2', 'Escape a chaotic alien planet by fighting through hordes of frenzied monsters – with your friends, or on your own. Combine loot in surprising ways and master each character until you become the havoc you feared upon your first crash landing.', 10, 1000, 1, 'price_1L5C2cGLO8h1ns7mG9mP0ghL', '\\img\\games\\risk-of-rain-2-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (56, 'Space Engineers', 'Space Engineers is a sandbox game about engineering, construction, exploration and survival in space and on planets. Players build space ships, space stations, planetary outposts of various sizes and uses, pilot ships and travel through space to explore planets and gather resources to survive.', 10, 1000, 1, 'price_1L5C5JGLO8h1ns7m29FKPYIZ', '\\img\\games\\space-engineers-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (57, 'Squad Dedicated Server', 'Squad is a tactical FPS that provides authentic combat experiences through teamwork, constant communication, and gameplay. It bridges the large gap between arcade shooter and military simulation with 100 player battles, combined arms combat, base building, and a great integrated VoIP system', 10, 1000, 1, 'price_1L5C5zGLO8h1ns7mWnEb1fWX', '\\img\\games\\squad-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (58, 'Starmade', 'The ultimate space sandbox. Participate in epic fleet battles, form alliances, strive to dominate entire galaxies and harness the universe’s resources for your industrious empire or the destruction of others. Customise your experience, the universe is yours!', 10, 1000, 1, 'price_1L5C6ZGLO8h1ns7mCDOelL66', '\\img\\games\\starmade-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (59, 'Stationeers', 'Stationeers puts you in control of the construction and management of a space station to run by yourself or online with your friends. Complex atmospheric, electrical, manufacturing, agriculture, and gravitational systems require your thought and management at all times!', 10, 1000, 1, 'price_1L5C76GLO8h1ns7mB1SNACyR', '\\img\\games\\stationeers-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (60, 'Sven Co-op', 'Sven Co-op is a co-operative game originally based around Valve Software''s Half-Life. In this game players must work together against computer controlled enemies and solve puzzles as a team.', 10, 1000, 1, 'price_1L5C7jGLO8h1ns7m3lmhskLV', '\\img\\games\\sven-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (62, 'Team Fortress 2', 'Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!', 10, 1000, 1, 'price_1L5CA4GLO8h1ns7mv89nexsG', '\\img\\games\\tf2-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (64, 'Team Fortress Classic', 'One of the most popular online action games of all time, Team Fortress Classic features over nine character classes -- from Medic to Spy to Demolition Man -- enlisted in a unique style of online team warfare. Each character class possesses unique weapons, items, and abilities', 10, 1000, 1, 'price_1L5CBRGLO8h1ns7m7jaqcKpe', '\\img\\games\\tf-classic-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (65, 'The Forest', 'As the lone survivor of a passenger jet crash, you find yourself in a mysterious forest battling to stay alive against a society of cannibalistic mutants. Build, explore, survive in this terrifying first person survival horror simulator.', 10, 1000, 1, 'price_1L5CCyGLO8h1ns7mXiVAOLt4', '\\img\\games\\the-forest-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (66, 'The Isle (Legacy)', 'Experience fierce open world survival gameplay as you attempt to stay alive on an unforgiving island inhabited by dinosaurs! Hunt. Grow. Survive.', 10, 1000, 1, 'price_1L5CDZGLO8h1ns7mipTIsXsQ', '\\img\\games\\the-isle-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (67, 'The Ship', 'The Ship is a murder mystery multiplayer.', 10, 1000, 1, 'price_1L5CE5GLO8h1ns7mhqqtaqC0', '\\img\\games\\the-ship.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (68, 'Unturned', 'You''re a survivor in the zombie infested ruins of society, and must work with your friends and forge alliances to remain among the living.', 10, 1000, 1, 'price_1L5CEtGLO8h1ns7mUY9ZcxJB', '\\img\\games\\unturned-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (69, 'Wurm Unlimited', 'Wurm Unlimited is the standalone version of the fantasy sandbox world Wurm Online, the MMORPG where the players are in charge! A pioneer in the ideas of player influence, crafting and adventure, it is now one of the most deep and feature packed true sandbox experiences available.', 10, 1000, 1, 'price_1L5CFYGLO8h1ns7mrf72ssso', '\\img\\games\\wurm-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (70, 'Zombie Panic Source', 'Dive into the zombie apocalypse with Zombie Panic! Source: a cooperative, survival-horror first-person-shooter. A fast-paced standalone modification.', 10, 1000, 1, 'price_1L5CGCGLO8h1ns7mGA52EiQK', '\\img\\games\\zombie-panic-logo.jpg');
INSERT INTO hardgaming.games (id, name, shortdesc, users, price, avail, sku, img) VALUES (71, 'ValheimPlus', 'Valheim with the 3rd party Valheim Plus mod pre-installed.', 10, 1000, 1, 'price_1L5CGmGLO8h1ns7mCCRixkTL', '\\img\\games\\valheim-plus-logo.png');
